Fix `uninitialized constant Puppet::Parameter::Boolean`
On Puppet 7, resource type generation via `puppet generate types`,
fails with the following error message:

```
Debug: Loading custom type 'podman_secret' in '.../modules/podman/lib/puppet/type/podman_secret.rb'.
Error: Failed to load custom type 'podman_secret' from '.../modules/podman/lib/puppet/type/podman_secret.rb': uninitialized constant Puppet::Parameter::Boolean
```

Adding an explicit require fixes this issue.